import 'dart:math';
import 'models.dart';

const Map<Lang, Map<String, String>> TR = {
  Lang.ku: {
    "appName":"MM House", "pos":"کاشیر", "history":"مێژووی فرۆشتن", "daily":"ڕاپۆرتی ڕۆژانە",
    "monthly":"ڕاپۆرتی مانگانە", "yearly":"ڕاپۆرتی ساڵانە", "menuMgmt":"بەڕێوەبردنی مینیۆ",
    "settings":"ڕێکخستنەکان", "logout":"چوونەدەرەوە", "all":"هەموو",
    "newOrder":"داواکاری نوێ", "clearOrder":"سڕینەوە", "checkout":"پرداخت", "print":"چاپکردن",
    "subtotal":"کۆی جیاواز", "discount":"داشکاندن", "total":"کۆی گشتی",
    "paid":"پرداخت کرا", "change":"پاشگەڕاندنەوە", "cash":"نەقد", "card":"کارت",
    "orderNum":"ژمارەی داواکاری", "cashier":"کاشیر", "totalRevenue":"کۆی داهات",
    "totalOrders":"کۆی داواکاری", "avgOrder":"ناوەندی داواکاری", "bestItems":"باشترین بابەتەکان",
    "bestCats":"باشترین جۆرەکان", "payBreakdown":"جۆری پرداخت", "salesTrend":"ڕوانگەی فرۆشتن",
    "thankYou":"سوپاس بۆ داواکاریەکەتان", "active":"چالاک", "inactive":"ناچالاک",
    "save":"پاشەکەوتکردن", "language":"زمان", "kurdish":"کوردی (سۆرانی)", "arabic":"عەرەبی",
    "confirmClear":"دڵنیای لە سڕینەوەی داواکاری؟", "yes":"بەڵێ", "no":"نەخێر",
    "reprint":"دووبارە چاپکردن", "status":"دۆخ", "completed":"تەواوبوو",
    "cancelled":"هەڵوەشاوە", "refunded":"گەڕاندرایەوە", "receipt":"وەصل", "close":"داخستن",
    "payMethod":"جۆری پرداخت", "addItem":"زیادکردنی بابەتێک", "editItem":"دەستکاریکردن",
    "kurdishName":"ناوی کوردی", "arabicName":"ناوی عەرەبی", "price":"نرخ",
    "category":"جۆر", "actions":"کردارەکان", "from":"لە", "to":"بۆ",
    "cashierName":"ناوی کاشیر", "qty":"ژمارە", "searchPlaceholder":"گەڕان بکە...",
    "revenue":"داهات", "orders":"داواکاری", "filterDate":"فلتەری بەروار",
    "emptyCart":"داواکاری بەتاڵە", "confirmPayment":"پشتڕاستکردنەوەی پرداخت",
    "enterPaid":"بڕی پرداخت بنووسە", "printerSettings":"ڕێکخستنی چاپکەر",
    "appSettings":"ڕێکخستنی سیستەم", "name":"ناو",
    "profileSettings": "ڕێکخستنی پرۆفایل",
  },
  Lang.ar: {
    "appName":"MM House", "pos":"الكاشير", "history":"سجل المبيعات", "daily":"التقارير اليومية",
    "monthly":"التقارير الشهرية", "yearly":"التقارير السنوية", "menuMgmt":"إدارة القائمة",
    "settings":"الإعدادات", "logout":"تسجيل الخروج", "all":"الكل",
    "newOrder":"طلب جديد", "clearOrder":"مسح", "checkout":"الدفع", "print":"طباعة",
    "subtotal":"المجموع الفرعي", "discount":"الخصم", "total":"المجموع الكلي",
    "paid":"المدفوع", "change":"الباقي", "cash":"نقدي", "card":"بطاقة",
    "orderNum":"رقم الطلب", "cashier":"الكاشير", "totalRevenue":"إجمالي الإيرادات",
    "totalOrders":"إجمالي الطلبات", "avgOrder":"متوسط الطلب", "bestItems":"أفضل العناصر",
    "bestCats":"أفضل الفئات", "payBreakdown":"تفصيل الدفع", "salesTrend":"مؤشر المبيعات",
    "thankYou":"شكراً لطلبكم", "active":"نشط", "inactive":"غير نشط",
    "save":"حفظ", "language":"اللغة", "kurdish":"الكردية (السورانية)", "arabic":"العربية",
    "confirmClear":"هل أنت متأكد من مسح الطلب؟", "yes":"نعم", "no":"لا",
    "reprint":"إعادة الطباعة", "status":"الحالة", "completed":"مكتمل",
    "cancelled":"ملغى", "refunded":"مسترد", "receipt":"الفاتورة", "close":"إغلاق",
    "payMethod":"طريقة الدفع", "addItem":"إضافة عنصر", "editItem":"تعديل",
    "kurdishName":"الاسم الكردي", "arabicName":"الاسم العربي", "price":"السعر",
    "category":"الفئة", "actions":"الإجراءات", "from":"من", "to":"إلى",
    "cashierName":"اسم الكاشير", "qty":"الكمية", "searchPlaceholder":"ابحث...",
    "revenue":"الإيرادات", "orders":"الطلبات", "filterDate":"تصفية بالتاريخ",
    "emptyCart":"الطلب فارغ", "confirmPayment":"تأكيد الدفع",
    "enterPaid":"أدخل المبلغ المدفوع", "printerSettings":"إعدادات الطابعة",
    "appSettings":"إعدادات النظام", "name":"الاسم",
    "profileSettings": "إعدادات الملف الشخصي",
  }
};

const Map<String, Map<Lang, String>> CATS = {
  "pasta":    { Lang.ku:"پاستا و برینج",        Lang.ar:"معكرونة وأرز" },
  "grills":   { Lang.ku:"کباب و خواردنی تەواو", Lang.ar:"مشاوي وأكلات تقليدية" },
  "shawarma": { Lang.ku:"شاوەرما و بێرگەر",     Lang.ar:"شاورما وبرجر" },
  "kentucky": { Lang.ku:"کینتاکی",              Lang.ar:"كنتاكي" },
  "sides":    { Lang.ku:"خواردنی لاوەکی",       Lang.ar:"مقبلات وأطباق جانبية" },
  "drinks":   { Lang.ku:"خواردنەوە",            Lang.ar:"مشروبات" },
};

String u(String id) => 'https://images.unsplash.com/photo-$id?w=320&h=220&fit=crop&auto=format&q=80';

final List<MenuItemModel> INITIAL_MENU = [
  MenuItemModel(
    id: "p01",
    categoryId: "pasta",
    nameKu: "پاستای ئەلفریدۆ",
    nameAr: "معكرونة الفريدو",
    nameEn: "Alfredo Pasta",
    priceIQD: 5000.0,
    imageSearchQuery: "alfredo pasta plate",
    imageUrl: "https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?w=320&h=220&fit=crop&auto=format&q=80",
    isAvailable: true,
  ),
  MenuItemModel(
    id: "p02",
    categoryId: "pasta",
    nameKu: "پاستای ئەلفریدۆ لەگەڵ گۆشت",
    nameAr: "معكرونة الفريدو باللحم",
    nameEn: "Alfredo Pasta with Meat",
    priceIQD: 5000.0,
    imageSearchQuery: "alfredo pasta plate meat",
    imageUrl: "https://images.unsplash.com/photo-1563379926898-05f4575a45d8?w=320&h=220&fit=crop&auto=format&q=80",
    isAvailable: true,
  ),
  MenuItemModel(
    id: "p03",
    categoryId: "pasta",
    nameKu: "پاستای سۆسی سوور لەگەڵ مریشک",
    nameAr: "معكرونة صلصة حمراء بالدجاج",
    nameEn: "Red Sauce Pasta with Chicken",
    priceIQD: 5000.0,
    imageSearchQuery: "red sauce pasta chicken",
    imageUrl: "https://images.unsplash.com/photo-1567608346072-b31551b7ee48?w=320&h=220&fit=crop&auto=format&q=80",
    isAvailable: true,
  ),
  MenuItemModel(
    id: "p04",
    categoryId: "pasta",
    nameKu: "پاستای سۆسی تێکەڵ",
    nameAr: "معكرونة بصلصات مشكلة",
    nameEn: "Mixed Sauce Pasta",
    priceIQD: 5000.0,
    imageSearchQuery: "mixed sauce pasta",
    imageUrl: "https://placehold.co/400x400/2C3E50/FFFFFF?text=mixed%20sauce%20pasta",
    isAvailable: true,
  ),
  MenuItemModel(
    id: "p05",
    categoryId: "pasta",
    nameKu: "پاستای سۆس و گۆشت",
    nameAr: "معكرونة بالصلصة واللحم",
    nameEn: "Pasta with Sauce and Meat",
    priceIQD: 5000.0,
    imageSearchQuery: "pasta meat sauce",
    imageUrl: "https://placehold.co/400x400/2C3E50/FFFFFF?text=pasta%20meat%20sauce",
    isAvailable: true,
  ),
  MenuItemModel(
    id: "p06",
    categoryId: "pasta",
    nameKu: "پاستای موزاریلا",
    nameAr: "معكرونة بجبن الموزاريلا",
    nameEn: "Mozzarella Pasta",
    priceIQD: 6000.0,
    imageSearchQuery: "mozzarella pasta plate",
    imageUrl: "https://images.unsplash.com/photo-1569050467447-ce54b3bbc37d?w=320&h=220&fit=crop&auto=format&q=80",
    isAvailable: true,
  ),
  MenuItemModel(
    id: "p07",
    categoryId: "pasta",
    nameKu: "ریزۆ",
    nameAr: "ريزو",
    nameEn: "Rizo",
    priceIQD: 5000.0,
    imageSearchQuery: "rizo chicken rice",
    imageUrl: "https://images.unsplash.com/photo-1476124369491-e7addf5db371?w=320&h=220&fit=crop&auto=format&q=80",
    isAvailable: true,
  ),
  MenuItemModel(
    id: "p08",
    categoryId: "pasta",
    nameKu: "برنج و شلە",
    nameAr: "أرز مع المرق (شيلة)",
    nameEn: "Rice with Shila",
    priceIQD: 3000.0,
    imageSearchQuery: "rice stew plate",
    imageUrl: "https://placehold.co/400x400/2C3E50/FFFFFF?text=rice%20stew%20plate",
    isAvailable: true,
  ),
  MenuItemModel(
    id: "p09",
    categoryId: "pasta",
    nameKu: "کباب لەگەڵ برینج",
    nameAr: "كباب مع أرز",
    nameEn: "Kebab with Rice",
    priceIQD: 5000.0,
    imageSearchQuery: "kebab rice plate",
    imageUrl: "https://images.unsplash.com/photo-1544025162-d76538fd41e3?w=320&h=220&fit=crop&auto=format&q=80",
    isAvailable: true,
  ),
  MenuItemModel(
    id: "p10",
    categoryId: "pasta",
    nameKu: "تکەیی مریشک لەگەڵ برینج",
    nameAr: "تکەی دجاج مع أرز",
    nameEn: "Chicken Tikka with Rice",
    priceIQD: 4000.0,
    imageSearchQuery: "chicken tikka rice plate",
    imageUrl: "https://images.unsplash.com/photo-1598103442097-8b74394b95c8?w=320&h=220&fit=crop&auto=format&q=80",
    isAvailable: true,
  ),
  MenuItemModel(
    id: "p11",
    categoryId: "pasta",
    nameKu: "تکەیی گۆشت لەگەڵ برینج",
    nameAr: "تکەی لحم مع أرز",
    nameEn: "Meat Tikka with Rice",
    priceIQD: 5000.0,
    imageSearchQuery: "meat tikka rice plate",
    imageUrl: "https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=320&h=220&fit=crop&auto=format&q=80",
    isAvailable: true,
  ),
  MenuItemModel(
    id: "p12",
    categoryId: "pasta",
    nameKu: "بریانی MM House",
    nameAr: "برياني MM House",
    nameEn: "MM House Biryani",
    priceIQD: 5000.0,
    imageSearchQuery: "biryani plate",
    imageUrl: "https://images.unsplash.com/photo-1603360946369-dc9bb6258143?w=320&h=220&fit=crop&auto=format&q=80",
    isAvailable: true,
  ),
  MenuItemModel(
    id: "p13",
    categoryId: "pasta",
    nameKu: "برینج لەگەڵ تارێک",
    nameAr: "أرز مع تارێک",
    nameEn: "Rice with Chicken Quarter",
    priceIQD: 5500.0,
    imageSearchQuery: "chicken quarter rice plate",
    imageUrl: "https://images.unsplash.com/photo-1536304929831-ee1ca9d44906?w=320&h=220&fit=crop&auto=format&q=80",
    isAvailable: true,
  ),
  MenuItemModel(
    id: "p14",
    categoryId: "pasta",
    nameKu: "برینج لەگەڵ گەسی گۆشت",
    nameAr: "أرز مع گەس اللحم",
    nameEn: "Rice with Meat Gas",
    priceIQD: 5000.0,
    imageSearchQuery: "meat shawarma rice plate",
    imageUrl: "https://placehold.co/400x400/2C3E50/FFFFFF?text=meat%20shawarma%20rice%20plate",
    isAvailable: true,
  ),
  MenuItemModel(
    id: "p15",
    categoryId: "pasta",
    nameKu: "برینج لەگەڵ گەسی مریشک",
    nameAr: "أرز مع گەس الدجاج",
    nameEn: "Rice with Chicken Gas",
    priceIQD: 5000.0,
    imageSearchQuery: "chicken shawarma rice plate",
    imageUrl: "https://placehold.co/400x400/2C3E50/FFFFFF?text=chicken%20shawarma%20rice%20plate",
    isAvailable: true,
  ),
  MenuItemModel(
    id: "g01",
    categoryId: "grills",
    nameKu: "یەک شیش کەباب",
    nameAr: "شيش كباب واحد",
    nameEn: "One Shish Kebab",
    priceIQD: 3000.0,
    imageSearchQuery: "shish kebab skewer",
    imageUrl: "https://placehold.co/400x400/2C3E50/FFFFFF?text=shish%20kebab%20skewer",
    isAvailable: true,
  ),
  MenuItemModel(
    id: "g02",
    categoryId: "grills",
    nameKu: "جگەر",
    nameAr: "كبد",
    nameEn: "Liver",
    priceIQD: 3000.0,
    imageSearchQuery: "grilled liver skewers",
    imageUrl: "https://placehold.co/400x400/2C3E50/FFFFFF?text=grilled%20liver%20skewers",
    isAvailable: true,
  ),
  MenuItemModel(
    id: "g03",
    categoryId: "grills",
    nameKu: "تکەیی مریشک",
    nameAr: "تکەی دجاج",
    nameEn: "Chicken Tikka",
    priceIQD: 2000.0,
    imageSearchQuery: "chicken tikka skewers",
    imageUrl: "https://images.unsplash.com/photo-1532550907401-a500c9a57435?w=320&h=220&fit=crop&auto=format&q=80",
    isAvailable: true,
  ),
  MenuItemModel(
    id: "g04",
    categoryId: "grills",
    nameKu: "باڵی مریشک",
    nameAr: "أجنحة دجاج",
    nameEn: "Chicken Wings",
    priceIQD: 3500.0,
    imageSearchQuery: "grilled chicken wings plate",
    imageUrl: "https://images.unsplash.com/photo-1527477396000-e27163b481c2?w=320&h=220&fit=crop&auto=format&q=80",
    isAvailable: true,
  ),
  MenuItemModel(
    id: "g05",
    categoryId: "grills",
    nameKu: "دوو شیش کەباب",
    nameAr: "شيشتا كباب",
    nameEn: "Two Shish Kebabs",
    priceIQD: 9000.0,
    imageSearchQuery: "two shish kebabs plate",
    imageUrl: "https://placehold.co/400x400/2C3E50/FFFFFF?text=two%20shish%20kebabs%20plate",
    isAvailable: true,
  ),
  MenuItemModel(
    id: "g06",
    categoryId: "grills",
    nameKu: "سینی بڕژاوی تێکەڵی MM House",
    nameAr: "سینی بڕژاوی تێکەڵی MM House",
    nameEn: "MM House Mixed Grill",
    priceIQD: 25000.0,
    imageSearchQuery: "mixed grill meat plate",
    imageUrl: "https://placehold.co/400x400/2C3E50/FFFFFF?text=mixed%20grill%20meat%20plate",
    isAvailable: true,
  ),
  MenuItemModel(
    id: "g07",
    categoryId: "grills",
    nameKu: "یەک شیش کەباب تێکەڵ (محشی)",
    nameAr: "شيش كباب مشكل (محشي)",
    nameEn: "One Shish Kebab (Stuffed)",
    priceIQD: 3500.0,
    imageSearchQuery: "stuffed kebab plate",
    imageUrl: "https://placehold.co/400x400/2C3E50/FFFFFF?text=stuffed%20kebab%20plate",
    isAvailable: true,
  ),
  MenuItemModel(
    id: "g08",
    categoryId: "grills",
    nameKu: "تەشریب گەس",
    nameAr: "تەشریب گەس",
    nameEn: "Tashreeb Gas",
    priceIQD: 5000.0,
    imageSearchQuery: "tashreeb dish meat bread",
    imageUrl: "https://images.unsplash.com/photo-1529006557810-274b9b2fc783?w=320&h=220&fit=crop&auto=format&q=80",
    isAvailable: true,
  ),
  MenuItemModel(
    id: "g09",
    categoryId: "grills",
    nameKu: "مریشکی بڕژاو سادە",
    nameAr: "دجاج بڕژاو بسيط",
    nameEn: "Simple Grilled Chicken",
    priceIQD: 13000.0,
    imageSearchQuery: "grilled chicken plate",
    imageUrl: "https://placehold.co/400x400/2C3E50/FFFFFF?text=grilled%20chicken%20plate",
    isAvailable: true,
  ),
  MenuItemModel(
    id: "g10",
    categoryId: "grills",
    nameKu: "مریشکی بڕژاو لەگەڵ لیمۆ",
    nameAr: "دجاج بڕژاو بالليمون",
    nameEn: "Grilled Chicken with Lemon",
    priceIQD: 14000.0,
    imageSearchQuery: "grilled chicken lemon plate",
    imageUrl: "https://placehold.co/400x400/2C3E50/FFFFFF?text=grilled%20chicken%20lemon%20plate",
    isAvailable: true,
  ),
  MenuItemModel(
    id: "g11",
    categoryId: "grills",
    nameKu: "مریشکی بڕژاو لەگەڵ مەنگۆ",
    nameAr: "دجاج بڕژاو بالمانجو",
    nameEn: "Grilled Chicken with Mango",
    priceIQD: 14000.0,
    imageSearchQuery: "grilled chicken mango plate",
    imageUrl: "https://placehold.co/400x400/2C3E50/FFFFFF?text=grilled%20chicken%20mango%20plate",
    isAvailable: true,
  ),
  MenuItemModel(
    id: "g12",
    categoryId: "grills",
    nameKu: "مریشکی بڕژاو لەگەڵ بیبەر",
    nameAr: "دجاج بڕژاو بالفلفل",
    nameEn: "Grilled Chicken with Pepper",
    priceIQD: 14000.0,
    imageSearchQuery: "grilled chicken pepper plate",
    imageUrl: "https://placehold.co/400x400/2C3E50/FFFFFF?text=grilled%20chicken%20pepper%20plate",
    isAvailable: true,
  ),
  MenuItemModel(
    id: "g13",
    categoryId: "grills",
    nameKu: "ساندویچی گەسی مریشک",
    nameAr: "ساندويتش گەس دجاج",
    nameEn: "Chicken Gas Sandwich",
    priceIQD: 3500.0,
    imageSearchQuery: "chicken shawarma sandwich",
    imageUrl: "https://images.unsplash.com/photo-1550950158-d0d960dff596?w=320&h=220&fit=crop&auto=format&q=80",
    isAvailable: true,
  ),
  MenuItemModel(
    id: "g14",
    categoryId: "grills",
    nameKu: "گەسی گۆشت",
    nameAr: "گەس اللحم",
    nameEn: "Meat Gas",
    priceIQD: 4000.0,
    imageSearchQuery: "meat shawarma plate",
    imageUrl: "https://placehold.co/400x400/2C3E50/FFFFFF?text=meat%20shawarma%20plate",
    isAvailable: true,
  ),
  MenuItemModel(
    id: "g15",
    categoryId: "grills",
    nameKu: "یەک تەبسی گەسی گۆشت",
    nameAr: "صينية گەس لحم",
    nameEn: "Meat Gas Tray",
    priceIQD: 6000.0,
    imageSearchQuery: "meat shawarma tray",
    imageUrl: "https://placehold.co/400x400/2C3E50/FFFFFF?text=meat%20shawarma%20tray",
    isAvailable: true,
  ),
  MenuItemModel(
    id: "s01",
    categoryId: "shawarma",
    nameKu: "یەک تەبسی شاوەرما",
    nameAr: "صينية شاورما",
    nameEn: "Shawarma Tray",
    priceIQD: 6000.0,
    imageSearchQuery: "shawarma tray meal",
    imageUrl: "https://placehold.co/400x400/2C3E50/FFFFFF?text=shawarma%20tray%20meal",
    isAvailable: true,
  ),  MenuItemModel(
    id: "s02",
    categoryId: "shawarma",
    nameKu: "شاورمای مریشک",
    nameAr: "شاورما دجاج",
    nameEn: "Chicken Shawarma",
    priceIQD: 2000.0,
    imageSearchQuery: "chicken shawarma",
    imageUrl: "https://placehold.co/400x400/2C3E50/FFFFFF?text=chicken%20shawarma",
    isAvailable: true,
  ),  MenuItemModel(
    id: "s03",
    categoryId: "shawarma",
    nameKu: "شاورمای گۆشت",
    nameAr: "شاورما لحم",
    nameEn: "Meat Shawarma",
    priceIQD: 2500.0,
    imageSearchQuery: "meat shawarma",
    imageUrl: "https://placehold.co/400x400/2C3E50/FFFFFF?text=meat%20shawarma",
    isAvailable: true,
  ),  MenuItemModel(
    id: "s04",
    categoryId: "shawarma",
    nameKu: "بەرگر",
    nameAr: "برگر",
    nameEn: "Burger",
    priceIQD: 3500.0,
    imageSearchQuery: "burger",
    imageUrl: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=320&h=220&fit=crop&auto=format&q=80",
    isAvailable: true,
  ),  MenuItemModel(
    id: "s05",
    categoryId: "shawarma",
    nameKu: "بەرگری گۆشت لەگەڵ پەنیر",
    nameAr: "برگر لحم مع الجبن",
    nameEn: "Beef Burger with Cheese",
    priceIQD: 4000.0,
    imageSearchQuery: "beef cheeseburger",
    imageUrl: "https://placehold.co/400x400/2C3E50/FFFFFF?text=beef%20cheeseburger",
    isAvailable: true,
  ),  MenuItemModel(
    id: "s06",
    categoryId: "shawarma",
    nameKu: "بەرگری مریشک",
    nameAr: "برگر دجاج",
    nameEn: "Chicken Burger",
    priceIQD: 3000.0,
    imageSearchQuery: "chicken burger",
    imageUrl: "https://placehold.co/400x400/2C3E50/FFFFFF?text=chicken%20burger",
    isAvailable: true,
  ),  MenuItemModel(
    id: "s07",
    categoryId: "shawarma",
    nameKu: "بەرگری مریشک لەگەڵ پەنیر",
    nameAr: "برگر دجاج مع الجبن",
    nameEn: "Chicken Burger with Cheese",
    priceIQD: 3500.0,
    imageSearchQuery: "chicken cheeseburger",
    imageUrl: "https://placehold.co/400x400/2C3E50/FFFFFF?text=chicken%20cheeseburger",
    isAvailable: true,
  ),  MenuItemModel(
    id: "s08",
    categoryId: "shawarma",
    nameKu: "بەرگری بڕژاو",
    nameAr: "برگر بڕژاو على اللهب",
    nameEn: "Flame-Grilled Burger",
    priceIQD: 5000.0,
    imageSearchQuery: "flame grilled burger",
    imageUrl: "https://placehold.co/400x400/2C3E50/FFFFFF?text=flame%20grilled%20burger",
    isAvailable: true,
  ),  MenuItemModel(
    id: "k01",
    categoryId: "kentucky",
    nameKu: "کەنتاکی — یەک پارچە",
    nameAr: "كنتاكي — قطعة واحدة",
    nameEn: "Kentucky Chicken - 1 Piece",
    priceIQD: 2000.0,
    imageSearchQuery: "Kentucky chicken one piece",
    imageUrl: "https://images.unsplash.com/photo-1562967914-608f82629710?w=320&h=220&fit=crop&auto=format&q=80",
    isAvailable: true,
  ),  MenuItemModel(
    id: "k02",
    categoryId: "kentucky",
    nameKu: "کەنتاکی — دوو پارچە",
    nameAr: "كنتاكي — قطعتان",
    nameEn: "Kentucky Chicken - 2 Pieces",
    priceIQD: 4000.0,
    imageSearchQuery: "Kentucky chicken two pieces",
    imageUrl: "https://placehold.co/400x400/2C3E50/FFFFFF?text=Kentucky%20chicken%20two%20pieces",
    isAvailable: true,
  ),  MenuItemModel(
    id: "k03",
    categoryId: "kentucky",
    nameKu: "کەنتاکی — ٤–٥ پارچە",
    nameAr: "كنتاكي — ٤–٥ قطع",
    nameEn: "Kentucky Chicken - 4-5 Pieces",
    priceIQD: 7500.0,
    imageSearchQuery: "Kentucky chicken 4 to 5 pieces",
    imageUrl: "https://placehold.co/400x400/2C3E50/FFFFFF?text=Kentucky%20chicken%204%20to%205%20pieces",
    isAvailable: true,
  ),  MenuItemModel(
    id: "k04",
    categoryId: "kentucky",
    nameKu: "کەنتاکی — ٨ پارچە",
    nameAr: "كنتاكي — ٨ قطع",
    nameEn: "Kentucky Chicken - 8 Pieces",
    priceIQD: 14500.0,
    imageSearchQuery: "Kentucky chicken 8 pieces",
    imageUrl: "https://placehold.co/400x400/2C3E50/FFFFFF?text=Kentucky%20chicken%208%20pieces",
    isAvailable: true,
  ),  MenuItemModel(
    id: "a01",
    categoryId: "sides",
    nameKu: "باجی پیاز",
    nameAr: "باجي البصل",
    nameEn: "Onion Bhaji",
    priceIQD: 3000.0,
    imageSearchQuery: "onion bhaji",
    imageUrl: "https://images.unsplash.com/photo-1541014741259-de529411b96a?w=320&h=220&fit=crop&auto=format&q=80",
    isAvailable: true,
  ),  MenuItemModel(
    id: "a02",
    categoryId: "sides",
    nameKu: "سمبوسەی گۆشت",
    nameAr: "سمبوسة لحم",
    nameEn: "Meat Sambusa",
    priceIQD: 3500.0,
    imageSearchQuery: "meat sambusa",
    imageUrl: "https://images.unsplash.com/photo-1601050690597-df0568f70950?w=320&h=220&fit=crop&auto=format&q=80",
    isAvailable: true,
  ),  MenuItemModel(
    id: "a03",
    categoryId: "sides",
    nameKu: "سمبوسەی سەوزە",
    nameAr: "سمبوسة خضار",
    nameEn: "Vegetable Sambusa",
    priceIQD: 3000.0,
    imageSearchQuery: "vegetable sambusa",
    imageUrl: "https://placehold.co/400x400/2C3E50/FFFFFF?text=vegetable%20sambusa",
    isAvailable: true,
  ),  MenuItemModel(
    id: "a04",
    categoryId: "sides",
    nameKu: "فینگەری پەتاتە",
    nameAr: "بطاطا مقلية أصابع",
    nameEn: "Finger Fries",
    priceIQD: 2000.0,
    imageSearchQuery: "finger fries",
    imageUrl: "https://images.unsplash.com/photo-1573080496219-bb080dd4f877?w=320&h=220&fit=crop&auto=format&q=80",
    isAvailable: true,
  ),  MenuItemModel(
    id: "a05",
    categoryId: "sides",
    nameKu: "فینگەری پەتاتە لەگەڵ سۆس",
    nameAr: "بطاطا أصابع مع الصلصة",
    nameEn: "Finger Fries with Sauce",
    priceIQD: 2500.0,
    imageSearchQuery: "finger fries with sauce",
    imageUrl: "https://placehold.co/400x400/2C3E50/FFFFFF?text=finger%20fries%20with%20sauce",
    isAvailable: true,
  ),  MenuItemModel(
    id: "a06",
    categoryId: "sides",
    nameKu: "فینگەری وێج لەگەڵ گۆشت",
    nameAr: "بطاطا ويدجز مع اللحم",
    nameEn: "Finger Wedges with Meat",
    priceIQD: 6000.0,
    imageSearchQuery: "potato wedges with meat",
    imageUrl: "https://placehold.co/400x400/2C3E50/FFFFFF?text=potato%20wedges%20with%20meat",
    isAvailable: true,
  ),  MenuItemModel(
    id: "a07",
    categoryId: "sides",
    nameKu: "فینگەری وێج لەگەڵ سۆس",
    nameAr: "بطاطا ويدجز مع الصلصة",
    nameEn: "Finger Wedges with Sauce",
    priceIQD: 4000.0,
    imageSearchQuery: "potato wedges with sauce",
    imageUrl: "https://placehold.co/400x400/2C3E50/FFFFFF?text=potato%20wedges%20with%20sauce",
    isAvailable: true,
  ),  MenuItemModel(
    id: "a08",
    categoryId: "sides",
    nameKu: "فەلافل",
    nameAr: "فلافل",
    nameEn: "Falafel",
    priceIQD: 750.0,
    imageSearchQuery: "falafel",
    imageUrl: "https://placehold.co/400x400/2C3E50/FFFFFF?text=falafel",
    isAvailable: true,
  ),  MenuItemModel(
    id: "a09",
    categoryId: "sides",
    nameKu: "فەلافلی توند لەگەڵ نان",
    nameAr: "فلافل حار مع خبز النان",
    nameEn: "Spicy Falafel with Naan Bread",
    priceIQD: 1000.0,
    imageSearchQuery: "spicy falafel with naan bread",
    imageUrl: "https://placehold.co/400x400/2C3E50/FFFFFF?text=spicy%20falafel%20with%20naan%20bread",
    isAvailable: true,
  ),  MenuItemModel(
    id: "a10",
    categoryId: "sides",
    nameKu: "کروکێت",
    nameAr: "كروكيت",
    nameEn: "Croquette",
    priceIQD: 2500.0,
    imageSearchQuery: "croquette",
    imageUrl: "https://placehold.co/400x400/2C3E50/FFFFFF?text=croquette",
    isAvailable: true,
  ),  MenuItemModel(
    id: "a11",
    categoryId: "sides",
    nameKu: "ڕینگی پیاز",
    nameAr: "حلقات البصل",
    nameEn: "Onion Rings",
    priceIQD: 2500.0,
    imageSearchQuery: "onion rings",
    imageUrl: "https://placehold.co/400x400/2C3E50/FFFFFF?text=onion%20rings",
    isAvailable: true,
  ),  MenuItemModel(
    id: "a12",
    categoryId: "sides",
    nameKu: "موقەبیلاتی گەورە",
    nameAr: "صينية مقبلات كبيرة",
    nameEn: "Large Appetizer Platter",
    priceIQD: 4000.0,
    imageSearchQuery: "large appetizer platter",
    imageUrl: "https://images.unsplash.com/photo-1577303935007-0d306ee638cf?w=320&h=220&fit=crop&auto=format&q=80",
    isAvailable: true,
  ),  MenuItemModel(
    id: "a13",
    categoryId: "sides",
    nameKu: "موقەبیلاتی ناوەند",
    nameAr: "صينية مقبلات متوسطة",
    nameEn: "Medium Appetizer Platter",
    priceIQD: 3000.0,
    imageSearchQuery: "medium appetizer platter",
    imageUrl: "https://placehold.co/400x400/2C3E50/FFFFFF?text=medium%20appetizer%20platter",
    isAvailable: true,
  ),  MenuItemModel(
    id: "a14",
    categoryId: "sides",
    nameKu: "موقەبیلاتی بچووک",
    nameAr: "صينية مقبلات صغيرة",
    nameEn: "Small Appetizer Platter",
    priceIQD: 2000.0,
    imageSearchQuery: "small appetizer platter",
    imageUrl: "https://placehold.co/400x400/2C3E50/FFFFFF?text=small%20appetizer%20platter",
    isAvailable: true,
  ),  MenuItemModel(
    id: "d01",
    categoryId: "drinks",
    nameKu: "ئاو",
    nameAr: "ماء",
    nameEn: "Water",
    priceIQD: 250.0,
    imageSearchQuery: "bottled water",
    imageUrl: "https://images.unsplash.com/photo-1548839140-29a749e1cf4d?w=320&h=220&fit=crop&auto=format&q=80",
    isAvailable: true,
  ),  MenuItemModel(
    id: "d02",
    categoryId: "drinks",
    nameKu: "پەپسی",
    nameAr: "بيبسي",
    nameEn: "Pepsi",
    priceIQD: 500.0,
    imageSearchQuery: "Pepsi",
    imageUrl: "https://images.unsplash.com/photo-1622483767028-3f66f32aef97?w=320&h=220&fit=crop&auto=format&q=80",
    isAvailable: true,
  ),  MenuItemModel(
    id: "d03",
    categoryId: "drinks",
    nameKu: "کۆلا",
    nameAr: "كولا",
    nameEn: "Cola",
    priceIQD: 500.0,
    imageSearchQuery: "Cola",
    imageUrl: "https://placehold.co/400x400/2C3E50/FFFFFF?text=Cola",
    isAvailable: true,
  ),  MenuItemModel(
    id: "d04",
    categoryId: "drinks",
    nameKu: "سپرایت",
    nameAr: "سبرايت",
    nameEn: "Sprite",
    priceIQD: 500.0,
    imageSearchQuery: "Sprite",
    imageUrl: "https://placehold.co/400x400/2C3E50/FFFFFF?text=Sprite",
    isAvailable: true,
  ),  MenuItemModel(
    id: "d05",
    categoryId: "drinks",
    nameKu: "پەپسی دایت",
    nameAr: "بيبسي دايت",
    nameEn: "Diet Pepsi",
    priceIQD: 500.0,
    imageSearchQuery: "Diet Pepsi",
    imageUrl: "https://placehold.co/400x400/2C3E50/FFFFFF?text=Diet%20Pepsi",
    isAvailable: true,
  ),  MenuItemModel(
    id: "d06",
    categoryId: "drinks",
    nameKu: "پەپسی زێرۆ سەکر",
    nameAr: "بيبسي زيرو سكر",
    nameEn: "Pepsi Zero Sugar",
    priceIQD: 500.0,
    imageSearchQuery: "Pepsi Zero Sugar",
    imageUrl: "https://placehold.co/400x400/2C3E50/FFFFFF?text=Pepsi%20Zero%20Sugar",
    isAvailable: true,
  ),  MenuItemModel(
    id: "d07",
    categoryId: "drinks",
    nameKu: "دۆ",
    nameAr: "دۆ",
    nameEn: "Do",
    priceIQD: 1000.0,
    imageSearchQuery: "Do Kurdish traditional drink",
    imageUrl: "https://images.unsplash.com/photo-1558113583-d75f23fcb8a9?w=320&h=220&fit=crop&auto=format&q=80",
    isAvailable: true,
  ),
  MenuItemModel(
    id: "d08",
    categoryId: "drinks",
    nameKu: "ماستاو",
    nameAr: "ماستاو (عيران)",
    nameEn: "Mastaw",
    priceIQD: 1000.0,
    imageSearchQuery: "ayran yogurt drink glass",
    imageUrl: "https://placehold.co/400x400/2C3E50/FFFFFF?text=ayran%20yogurt%20drink%20glass",
    isAvailable: true,
  ),  MenuItemModel(
    id: "d09",
    categoryId: "drinks",
    nameKu: "میرەندا",
    nameAr: "ميرندا",
    nameEn: "Miranda",
    priceIQD: 500.0,
    imageSearchQuery: "Mirinda",
    imageUrl: "https://placehold.co/400x400/2C3E50/FFFFFF?text=Mirinda",
    isAvailable: true,
  ),  MenuItemModel(
    id: "d10",
    categoryId: "drinks",
    nameKu: "فەنتا",
    nameAr: "فانتا",
    nameEn: "Fanta",
    priceIQD: 500.0,
    imageSearchQuery: "Fanta",
    imageUrl: "https://placehold.co/400x400/2C3E50/FFFFFF?text=Fanta",
    isAvailable: true,
  ),  MenuItemModel(
    id: "d11",
    categoryId: "drinks",
    nameKu: "سێڤەن ئەپ",
    nameAr: "سفن أب",
    nameEn: "7 Up",
    priceIQD: 500.0,
    imageSearchQuery: "7UP",
    imageUrl: "https://placehold.co/400x400/2C3E50/FFFFFF?text=7UP",
    isAvailable: true,
  ),  MenuItemModel(
    id: "d12",
    categoryId: "drinks",
    nameKu: "چا",
    nameAr: "شاي",
    nameEn: "Tea",
    priceIQD: 250.0,
    imageSearchQuery: "Iraqi tea",
    imageUrl: "https://images.unsplash.com/photo-1564890369478-c89ca3d9cde4?w=320&h=220&fit=crop&auto=format&q=80",
    isAvailable: true,
  ),
];

List<Order> generateSampleOrders() {
  final cashiers = ["ئارام احمد", "هەردى كریم", "ساران محمد", "كارزان عبدالله"];
  final pool = [
    {"id": "p01", "nameKu": "پاستای ئەلفریدۆ", "nameAr": "معكرونة الفريدو", "price": 5000.0},
    {"id": "p06", "nameKu": "پاستای موزاریلا", "nameAr": "معكرونة بجبن الموزاريلا", "price": 6000.0},
    {"id": "p12", "nameKu": "بریانی MM House", "nameAr": "برياني MM House", "price": 5000.0},
    {"id": "g01", "nameKu": "یەک شیش کەباب", "nameAr": "شيش كباب واحد", "price": 3000.0},
    {"id": "g04", "nameKu": "باڵی مریشک", "nameAr": "أجنحة دجاج", "price": 3500.0},
    {"id": "g06", "nameKu": "سینی بڕژاوی تێکەڵی MM House", "nameAr": "سینی بڕژاوی تێکەڵی MM House", "price": 25000.0},
    {"id": "g09", "nameKu": "مریشکی بڕژاو سادە", "nameAr": "دجاج بڕژاو بسيط", "price": 13000.0},
    {"id": "s02", "nameKu": "شاوەرمای مریشک", "nameAr": "شاورما دجاج", "price": 2000.0},
    {"id": "s04", "nameKu": "بێرگەر", "nameAr": "برجر", "price": 3500.0},
    {"id": "s05", "nameKu": "بێرگەری گاوی لەگەڵ پەنیر", "nameAr": "برجر لحم بالجبن", "price": 4000.0},
    {"id": "k01", "nameKu": "مریشکی کینتاکی — ١ پارچە", "nameAr": "دجاج كنتاكي — قطعة", "price": 2000.0},
    {"id": "k03", "nameKu": "مریشکی کینتاکی — ٤-٥ پارچە", "nameAr": "دجاج كنتاكي — ٤-٥ قطع", "price": 7500.0},
    {"id": "a04", "nameKu": "فینگەر فرایز", "nameAr": "بطاطا مقلية", "price": 2000.0},
    {"id": "a08", "nameKu": "فەلافەل", "nameAr": "فلافل", "price": 750.0},
    {"id": "d01", "nameKu": "ئاو", "nameAr": "ماء", "price": 250.0},
    {"id": "d02", "nameKu": "پێپسی", "nameAr": "بيبسي", "price": 500.0},
    {"id": "d12", "nameKu": "چای", "nameAr": "شاي", "price": 250.0},
    {"id": "g02", "nameKu": "جگەر", "nameAr": "كبد", "price": 3000.0},
    {"id": "p09", "nameKu": "کباب لەگەڵ برینج", "nameAr": "كباب مع أرز", "price": 5000.0},
    {"id": "a01", "nameKu": "بەژێی پیاز", "nameAr": "باجي بصل", "price": 3000.0},
  ];

  final orders = <Order>[];
  final statuses = [
    OrderStatus.completed, OrderStatus.completed, OrderStatus.completed,
    OrderStatus.completed, OrderStatus.completed, OrderStatus.completed,
    OrderStatus.completed, OrderStatus.completed, OrderStatus.cancelled, OrderStatus.refunded
  ];
  int num = 1;
  final rnd = Random();

  for (int day = 45; day >= 0; day--) {
    final base = DateTime.now().subtract(Duration(days: day));
    final count = rnd.nextInt(8) + 5;
    
    for (int i = 0; i < count; i++) {
      final hr = 10 + rnd.nextInt(11);
      final mn = rnd.nextInt(60);
      final d = DateTime(base.year, base.month, base.day, hr, mn);
      
      final itemCount = rnd.nextInt(4) + 1;
      final items = <OrderItem>[];
      
      for (int j = 0; j < itemCount; j++) {
        final randomItem = pool[rnd.nextInt(pool.length)];
        final id = randomItem["id"] as String;
        final nameKu = randomItem["nameKu"] as String;
        final nameAr = randomItem["nameAr"] as String;
        final price = randomItem["price"] as double;
        final qty = rnd.nextInt(3) + 1;
        
        final existingIndex = items.indexWhere((x) => x.id == id);
        if (existingIndex != -1) {
          final old = items[existingIndex];
          items[existingIndex] = OrderItem(
            id: old.id,
            nameKu: old.nameKu,
            nameAr: old.nameAr,
            price: old.price,
            qty: old.qty + qty
          );
        } else {
          items.add(OrderItem(id: id, nameKu: nameKu, nameAr: nameAr, price: price, qty: qty));
        }
      }
      
      final subtotal = items.fold<double>(0, (s, x) => s + (x.price * x.qty));
      final discount = rnd.nextDouble() < 0.1 ? ((subtotal * 0.05 / 500).floor() * 500).toDouble() : 0.0;
      final total = subtotal - discount;
      
      final payMethod = rnd.nextDouble() < 0.72 ? PayMethod.cash : PayMethod.card;
      final paid = payMethod == PayMethod.cash ? ((total / 1000).ceil() * 1000).toDouble() : total;
      final status = statuses[rnd.nextInt(statuses.length)];
      
      orders.add(Order(
        id: 'ord_$num',
        numStr: num.toString().padLeft(4, '0'),
        date: d,
        cashier: cashiers[rnd.nextInt(cashiers.length)],
        items: items,
        subtotal: subtotal,
        discount: discount,
        total: total,
        payMethod: payMethod,
        paid: paid,
        change: paid - total,
        status: status,
      ));
      num++;
    }
  }
  orders.sort((a, b) => b.date.compareTo(a.date));
  return orders;
}
