// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCm8h27IQ5qkkdOnQDuMICsDKJJvxFgxnI',
    appId: '1:455061259677:web:0318c8e33677f8b71e9b74',
    messagingSenderId: '455061259677',
    projectId: 'resturant-9d4ed',
    authDomain: 'resturant-9d4ed.firebaseapp.com',
    storageBucket: 'resturant-9d4ed.firebasestorage.app',
    measurementId: 'G-4PN817SMCY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmavxv7m_FtdXu--N_3Ol2qNssf-nKQFw',
    appId: '1:455061259677:android:4e6a23a807739fc41e9b74',
    messagingSenderId: '455061259677',
    projectId: 'resturant-9d4ed',
    storageBucket: 'resturant-9d4ed.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRqV7u8_vsPaYglc4YKXOnQJNPyfhwZCg',
    appId: '1:455061259677:ios:3b7c49a6b5c39b421e9b74',
    messagingSenderId: '455061259677',
    projectId: 'resturant-9d4ed',
    storageBucket: 'resturant-9d4ed.firebasestorage.app',
    iosBundleId: 'com.example.restweb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRqV7u8_vsPaYglc4YKXOnQJNPyfhwZCg',
    appId: '1:455061259677:ios:3b7c49a6b5c39b421e9b74',
    messagingSenderId: '455061259677',
    projectId: 'resturant-9d4ed',
    storageBucket: 'resturant-9d4ed.firebasestorage.app',
    iosBundleId: 'com.example.restweb',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCm8h27IQ5qkkdOnQDuMICsDKJJvxFgxnI',
    appId: '1:455061259677:web:2b26493cf7d540c01e9b74',
    messagingSenderId: '455061259677',
    projectId: 'resturant-9d4ed',
    authDomain: 'resturant-9d4ed.firebaseapp.com',
    storageBucket: 'resturant-9d4ed.firebasestorage.app',
    measurementId: 'G-MNSDEC0HZ7',
  );
}
